### ISSUE TITLE
Hard coded path should be homebridge_dir

### ISSUE THREAD

**Issue by johnschult** [hannseman/ansible-homebridge#1]
https://github.com/hannseman/ansible-homebridge/blob/bd36ab264635e3073ac71cebffb1ef6b38b45c25/tasks/homebridge.yml#L35

Shouldn't this hard coded path in the template be the value of `homebridge_dir`? Otherwise if someone uses `/var/lib/homebridge` for `homebridge_dir` the file would be copied to the wrong location.

**Comment by hannseman** [comment]
Thanks for the report! You're totally right. Just pushed a fix for this.

**Comment by johnschult** [comment]
My pleasure 😇 

John

“It ain’t what you don’t know that gets you in trouble. It’s what you know for sure that just ain’t so. —Mark Twain
